CREATE PROCEDURE "T2"."TVI_A_IZZI"(IN IN_DATE VARCHAR(8)) 
LANGUAGE SQLSCRIPT AS
/*Variable de fecha*/
V_IN_DATE   VARCHAR(8) := '';
/****** 
 Calcula las migraciones, migraciones upsale, migraciones downsale, 
 migraciones nm de los clientes con orden tipo 100 en TVI a Izzi.
 Recalcula los indicadores en una ventana de 60 días
******/
BEGIN
/*Seteo de fecha*/
IF :IN_DATE = '' THEN
    V_IN_DATE := TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDD');
ELSE
    V_IN_DATE := IN_DATE;
END IF;
/*
 Calcula los clientes con orden de migración (100) en OI = 4 y calcula su 
 play_cli en base a la categoría de sus productos asociados que cumplen las 
 reglas de negocio en OI = 3 y 4. En base a la diferencia entre esos plays
 determina si se trata de un cliente con migración NM, DOWNSALE, UPSALE O 
 MIGRACION
*/
CREATE LOCAL TEMPORARY COLUMN TABLE "#MI_TVI" AS (
SELECT CLIENTE, MAX(PLAY_LEGACY) AS PLAY_LEGACY, MAX(PLAY_IZZI) AS PLAY_IZZI,
CASE 	WHEN MAX(PLAY_LEGACY) IS NULL OR MAX(PLAY_IZZI) IS NULL THEN 'NM'
		WHEN LENGTH(MAX(PLAY_LEGACY)) > LENGTH(MAX(PLAY_IZZI)) THEN 'DOWNSALE' 
		WHEN LENGTH(MAX(PLAY_LEGACY)) < LENGTH(MAX(PLAY_IZZI)) THEN 'UPSALE'
		WHEN LENGTH(MAX(PLAY_LEGACY)) = LENGTH(MAX(PLAY_IZZI)) THEN 'MIGRACION'
		END AS "TIPO"
		  FROM (
SELECT  CLIENTE , MAX(V)||MAX(I)||MAX(T) AS PLAY_LEGACY, 
	NULL AS PLAY_IZZI 
FROM (
	SELECT 	C.CLIENTE, 
		CASE WHEN P.CATEGORIA = 'VIDEO' 	THEN 'V' ELSE '' END AS V,
		CASE WHEN P.CATEGORIA = 'INTERNET' 	THEN 'I' ELSE '' END AS I,
		CASE WHEN P.CATEGORIA = 'TELEFONIA'	THEN 'T' ELSE '' END AS T
	FROM 	T1.HANA_STG1_MT_CLIENTES C,
			T1.HANA_STG1_MT_ORDENES O,
			T1.HANA_STG1_CAT_TIPO_ORD T,
			T1.HANA_STG1_MT_ORDENES_ITEM I,
			T1.HANA_STG1_CAT_PRODUCTOS P		
	WHERE	C.CTA_MIGRADA 	= 	O.CLIENTE_ID 
		AND	O.ORIG_ID 		= 	T.ORIG_ID
		AND	O.TIPO_ORDEN_ID = 	T.ID
		AND O.ORIG_ID		=	I.ORIG_ID
		AND	O.NO_ORDEN		=	I.ORDER_ID
		AND	I.ORIG_ID		=	P.ORIG_ID
		AND	I.PRODUCTO_ID	=	P.ID
		AND	C.ORIG_ID = 3
		AND O.ORIG_ID = 4	
		AND	FLG_CTE_MIGRADO = 'Y'
		AND	O.TIPO_ORDEN_ID = '100' --Orden de Migración Izzi
		AND	UPPER(P.TIPO) IN ('SERVICIO')
		AND	UPPER(P.PRODUCTO) NOT IN ('SERVICIOS ON DEMAND')	
)
GROUP BY CLIENTE
UNION ALL	
SELECT  CLIENTE, NULL AS PLAY_LEGACY, 
	 MAX(V)||MAX(I)||MAX(T) AS PLAY_IZZI 
FROM (
	SELECT C.CLIENTE, 
		CASE WHEN P.CATEGORIA = 'VIDEO' 	THEN 'V' ELSE '' END AS V,
		CASE WHEN P.CATEGORIA = 'INTERNET' 	THEN 'I' ELSE '' END AS I,
		CASE WHEN P.CATEGORIA = 'TELEFONIA'	THEN 'T' ELSE '' END AS T
	FROM 	T1.HANA_STG1_MT_CLIENTES C,
			T1.HANA_STG1_MT_ORDENES O,
			T1.HANA_STG1_CAT_TIPO_ORD T,
			T1.HANA_STG1_MT_ORDENES_ITEM I,
			T1.HANA_STG1_CAT_ITEMS_RGU P,
			T1.HANA_STG1_DIM_REGION R,
			T1.HANA_STG1_CAT_ORD_ESTATUS E
	WHERE	C.ORIG_ID		=	O.ORIG_ID
		AND	C.CLIENTE 		= 	O.CLIENTE_ID 
		AND	O.ORIG_ID 		= 	T.ORIG_ID
		AND	O.TIPO_ORDEN_ID = 	T.ID
		AND O.ORIG_ID		=	I.ORIG_ID
		AND	O.NO_ORDEN		=	I.ORDER_ID
		AND	I.ORIG_ID		=	P.ORIG_ID
		AND	I.PRODUCTO_ID	=	P.ID_PRODUCTO
		AND C.CIUDAD_ID		=	R.ID
		AND O.ORIG_ID		=	E.ORIG_ID
		AND O.ESTATUS_ORD_ID	=	E.ID
		AND	FLG_CTE_MIGRADO = 'Y'
		AND	P.KPI = '1'
		AND (R.REGION = 'NORESTE' OR R.REGION = 'ND') 
		AND UPPER(E.ESTATUS) != 'CANCELADO'
		AND T.TIPO_ORDEN = 'INSTALACION'
--		AND O.FECHA_CREACION BETWEEN ADD_DAYS(:V_IN_DATE,-60) 
--								AND :V_IN_DATE
)
GROUP BY CLIENTE
)
GROUP BY CLIENTE
);

--****************************************** 
-- Borramos registros existentes para evitar duplicidades
-- de Cliente
DELETE FROM  "T2"."HANA_STG1_ORDERS"
WHERE FECHA BETWEEN ADD_DAYS(:V_IN_DATE,-61) 
								AND :V_IN_DATE
AND ORIG_ID = 3 
AND (MIGRACIONES_IZZI_UPSALE 		IS NOT NULL
	OR MIGRACIONES_IZZI				IS NOT NULL
	OR MIGRACIONES_IZZI_DOWNSALE	IS NOT NULL
	OR MIGRACIONES_IZZI_NM			IS NOT NULL
	)
AND ID_REGION IN
	(SELECT ID AS ID_REGION 
	 FROM "T1"."HANA_STG1_DIM_REGION"
	 WHERE (REGION = 'NORESTE' OR REGION = 'ND'))
AND CLIENTE IN
	(SELECT DISTINCT CLIENTE
	 FROM "#MI_TVI")
;


--UPSALE
INSERT INTO "T2"."HANA_STG1_ORDERS"
("ORIG_ID","ID_REGION","ID_EMPRESA","ID_PRODUCTOS","NO_ORDEN","CLIENTE",
"CATEGORIA","PLAY_ORD","PLAY_CLI","FECHA","MES_1","ANIO_1",
"MIGRACIONES_IZZI_UPSALE", "MIGRACIONES_IZZI_INSTALACIONES")
SELECT DISTINCT 
	3 AS ORIG_ID , C.CIUDAD_ID AS ID_REGION, 3 AS ID_EMPRESA, P.ID_PRODUCTO 
	AS ID_PRODUCTOS, O.NO_ORDEN, C.CLIENTE, P.CATEGORIA, 
	MAP (LENGTH (M.PLAY_IZZI),  1, '1 PLAY',  2, '2 PLAY',  3, '3 PLAY') 
	AS PLAY_ORD, M.PLAY_IZZI, O.FECHA_CREACION AS FECHA, 
	ADD_MONTHS(O.FECHA_CREACION,1) AS MES_1,
	ADD_YEARS(O.FECHA_CREACION,1) AS ANIO_1, 1 AS MIGRACIONES_IZZI_UPSALE,
	CASE WHEN FECHA_PROGRAMACION IS NOT NULL AND UPPER(E.ESTATUS) 
		IN ('COMPLETA', 'FINALIZADA', 'ENVIADA') THEN 1 END 
		AS MIGRACIONES_IZZI_INSTALACIONES
FROM 		T1.HANA_STG1_MT_CLIENTES C,
			T1.HANA_STG1_MT_ORDENES O,
			T1.HANA_STG1_CAT_TIPO_ORD T,
			T1.HANA_STG1_MT_ORDENES_ITEM I,
			T1.HANA_STG1_CAT_ITEMS_RGU P,
			T1.HANA_STG1_DIM_REGION R,
			T1.HANA_STG1_CAT_ORD_ESTATUS E,
			"#MI_TVI" M
	WHERE	C.ORIG_ID		=	O.ORIG_ID
		AND	C.CLIENTE 		= 	O.CLIENTE_ID 
		AND	O.ORIG_ID 		= 	T.ORIG_ID
		AND	O.TIPO_ORDEN_ID = 	T.ID
		AND O.ORIG_ID		=	I.ORIG_ID
		AND	O.NO_ORDEN		=	I.ORDER_ID
		AND	I.ORIG_ID		=	P.ORIG_ID
		AND	I.PRODUCTO_ID	=	P.ID_PRODUCTO
		AND C.CIUDAD_ID		=	R.ID
		AND O.ORIG_ID		=	E.ORIG_ID
		AND O.ESTATUS_ORD_ID	=	E.ID
		AND C.CLIENTE 		=	M.CLIENTE
		AND C.CLIENTE IN (
	SELECT CLIENTE 
	FROM "#MI_TVI"
	WHERE TIPO = 'UPSALE'
				)
		AND C.ORIG_ID = 3
		AND	P.KPI = '1'
		AND UPPER(E.ESTATUS) != 'CANCELADO'
		AND T.TIPO_ORDEN = 'INSTALACION'
		AND CASE WHEN LOCATE(M.PLAY_LEGACY, 
		CASE WHEN CATEGORIA = 'VIDEO' THEN 'V' 
		 WHEN CATEGORIA = 'INTERNET' THEN 'I'
		 WHEN CATEGORIA = 'TELEFONIA' THEN 'T'
		END) != '0' THEN 1 END IS NULL	
		AND O.FECHA_CREACION BETWEEN ADD_DAYS(:V_IN_DATE,-60) 
								AND :V_IN_DATE
;

--MIGRACIONES
INSERT INTO "T2"."HANA_STG1_ORDERS"
("ORIG_ID","ID_REGION","ID_EMPRESA","ID_PRODUCTOS","NO_ORDEN","CLIENTE",
"CATEGORIA","PLAY_ORD","PLAY_CLI","FECHA","MES_1","ANIO_1",
"MIGRACIONES_IZZI", "MIGRACIONES_IZZI_REALIZADAS")
SELECT DISTINCT 
	3 AS ORIG_ID , C.CIUDAD_ID AS ID_REGION, 3 AS ID_EMPRESA, 
	P.ID_PRODUCTO AS ID_PRODUCTOS, O.NO_ORDEN, C.CLIENTE, P.CATEGORIA, 
	MAP (LENGTH (M.PLAY_IZZI),  1, '1 PLAY',  2, '2 PLAY',  3, '3 PLAY') 
	AS PLAY_ORD, M.PLAY_IZZI, O.FECHA_CREACION AS FECHA, 
	ADD_MONTHS(O.FECHA_CREACION,1) AS MES_1,
	ADD_YEARS(O.FECHA_CREACION,1) AS ANIO_1, 1 AS MIGRACIONES_IZZI,
	CASE WHEN FECHA_PROGRAMACION IS NOT NULL AND UPPER(E.ESTATUS) 
		IN ('COMPLETA', 'FINALIZADA', 'ENVIADA') THEN 1 END 
		AS MIGRACIONES_IZZI_REALIZADAS
FROM 		T1.HANA_STG1_MT_CLIENTES C,
			T1.HANA_STG1_MT_ORDENES O,
			T1.HANA_STG1_CAT_TIPO_ORD T,
			T1.HANA_STG1_MT_ORDENES_ITEM I,
			T1.HANA_STG1_CAT_ITEMS_RGU P,
			T1.HANA_STG1_DIM_REGION R,
			T1.HANA_STG1_CAT_ORD_ESTATUS E,
			"#MI_TVI" M		
	WHERE	C.ORIG_ID		=	O.ORIG_ID
		AND	C.CLIENTE 		= 	O.CLIENTE_ID 
		AND	O.ORIG_ID 		= 	T.ORIG_ID
		AND	O.TIPO_ORDEN_ID = 	T.ID
		AND O.ORIG_ID		=	I.ORIG_ID
		AND	O.NO_ORDEN		=	I.ORDER_ID
		AND	I.ORIG_ID		=	P.ORIG_ID
		AND	I.PRODUCTO_ID	=	P.ID_PRODUCTO
		AND C.CIUDAD_ID		=	R.ID
		AND O.ORIG_ID		=	E.ORIG_ID
		AND O.ESTATUS_ORD_ID	=	E.ID
		AND C.CLIENTE 		=	M.CLIENTE
		AND C.CLIENTE IN (
	SELECT CLIENTE 
	FROM "#MI_TVI"
	WHERE TIPO = 'MIGRACION'
				)
		AND C.ORIG_ID = 3
		AND	P.KPI = '1'
		AND UPPER(E.ESTATUS) != 'CANCELADO'
		AND T.TIPO_ORDEN = 'INSTALACION'
		AND O.FECHA_CREACION BETWEEN ADD_DAYS(:V_IN_DATE,-60) 
								AND :V_IN_DATE
UNION ALL
SELECT DISTINCT 
	3 AS ORIG_ID , C.CIUDAD_ID AS ID_REGION, 3 AS ID_EMPRESA, 
	P.ID_PRODUCTO AS ID_PRODUCTOS, O.NO_ORDEN, C.CLIENTE, P.CATEGORIA, 
	MAP (LENGTH (M.PLAY_IZZI),  1, '1 PLAY',  2, '2 PLAY',  3, '3 PLAY') 
	AS PLAY_ORD, M.PLAY_IZZI, O.FECHA_CREACION AS FECHA, 
	ADD_MONTHS(O.FECHA_CREACION,1) AS MES_1,
	ADD_YEARS(O.FECHA_CREACION,1) AS ANIO_1, 1 AS MIGRACIONES_IZZI,
	CASE WHEN FECHA_PROGRAMACION IS NOT NULL AND UPPER(E.ESTATUS) 
		IN ('COMPLETA', 'FINALIZADA', 'ENVIADA') THEN 1 END 
		AS MIGRACIONES_IZZI_REALIZADAS
FROM 		T1.HANA_STG1_MT_CLIENTES C,
			T1.HANA_STG1_MT_ORDENES O,
			T1.HANA_STG1_CAT_TIPO_ORD T,
			T1.HANA_STG1_MT_ORDENES_ITEM I,
			T1.HANA_STG1_CAT_ITEMS_RGU P,
			T1.HANA_STG1_DIM_REGION R,
			T1.HANA_STG1_CAT_ORD_ESTATUS E,
			"#MI_TVI" M		
	WHERE	C.ORIG_ID		=	O.ORIG_ID
		AND	C.CLIENTE 		= 	O.CLIENTE_ID 
		AND	O.ORIG_ID 		= 	T.ORIG_ID
		AND	O.TIPO_ORDEN_ID = 	T.ID
		AND O.ORIG_ID		=	I.ORIG_ID
		AND	O.NO_ORDEN		=	I.ORDER_ID
		AND	I.ORIG_ID		=	P.ORIG_ID
		AND	I.PRODUCTO_ID	=	P.ID_PRODUCTO
		AND C.CIUDAD_ID		=	R.ID
		AND O.ORIG_ID		=	E.ORIG_ID
		AND O.ESTATUS_ORD_ID	=	E.ID
		AND C.CLIENTE 		=	M.CLIENTE
		AND C.CLIENTE IN (
	SELECT CLIENTE 
	FROM "#MI_TVI"
	WHERE TIPO = 'UPSALE'
				)
		AND C.ORIG_ID = 3
		AND	P.KPI = '1'
		AND UPPER(E.ESTATUS) != 'CANCELADO'
		AND T.TIPO_ORDEN = 'INSTALACION'
		AND CASE WHEN LOCATE(M.PLAY_LEGACY, 
		CASE WHEN CATEGORIA = 'VIDEO' THEN 'V' 
		 WHEN CATEGORIA = 'INTERNET' THEN 'I'
		 WHEN CATEGORIA = 'TELEFONIA' THEN 'T'
		END) != '0' THEN 1 END IS NOT NULL	
		AND O.FECHA_CREACION BETWEEN ADD_DAYS(:V_IN_DATE,-60) 
								AND :V_IN_DATE
UNION ALL
SELECT DISTINCT 
	3 AS ORIG_ID , C.CIUDAD_ID AS ID_REGION, 3 AS ID_EMPRESA, 
	P.ID_PRODUCTO AS ID_PRODUCTOS, O.NO_ORDEN, C.CLIENTE, P.CATEGORIA, 
	MAP (LENGTH (M.PLAY_IZZI),  1, '1 PLAY',  2, '2 PLAY',  3, '3 PLAY') 
	AS PLAY_ORD, M.PLAY_IZZI, O.FECHA_CREACION AS FECHA, 
	ADD_MONTHS(O.FECHA_CREACION,1) AS MES_1,
	ADD_YEARS(O.FECHA_CREACION,1) AS ANIO_1, 1 AS MIGRACIONES_IZZI,
	CASE WHEN FECHA_PROGRAMACION IS NOT NULL AND UPPER(E.ESTATUS) 
		IN ('COMPLETA', 'FINALIZADA', 'ENVIADA') THEN 1 END 
		AS MIGRACIONES_IZZI_REALIZADAS
FROM 		T1.HANA_STG1_MT_CLIENTES C,
			T1.HANA_STG1_MT_ORDENES O,
			T1.HANA_STG1_CAT_TIPO_ORD T,
			T1.HANA_STG1_MT_ORDENES_ITEM I,
			T1.HANA_STG1_CAT_ITEMS_RGU P,
			T1.HANA_STG1_DIM_REGION R,
			T1.HANA_STG1_CAT_ORD_ESTATUS E,
			"#MI_TVI" M		
	WHERE	C.ORIG_ID		=	O.ORIG_ID
		AND	C.CLIENTE 		= 	O.CLIENTE_ID 
		AND	O.ORIG_ID 		= 	T.ORIG_ID
		AND	O.TIPO_ORDEN_ID = 	T.ID
		AND O.ORIG_ID		=	I.ORIG_ID
		AND	O.NO_ORDEN		=	I.ORDER_ID
		AND	I.ORIG_ID		=	P.ORIG_ID
		AND	I.PRODUCTO_ID	=	P.ID_PRODUCTO
		AND C.CIUDAD_ID		=	R.ID
		AND O.ORIG_ID		=	E.ORIG_ID
		AND O.ESTATUS_ORD_ID	=	E.ID
		AND C.CLIENTE 		=	M.CLIENTE
		AND C.CLIENTE IN (
	SELECT CLIENTE 
	FROM "#MI_TVI"
	WHERE TIPO = 'DOWNSALE'
				)
		AND C.ORIG_ID = 3
		AND	P.KPI = '1'
		AND UPPER(E.ESTATUS) != 'CANCELADO'
		AND T.TIPO_ORDEN = 'INSTALACION'
		AND O.FECHA_CREACION BETWEEN ADD_DAYS(:V_IN_DATE,-60) 
								AND :V_IN_DATE
;

--DOWNSALE
INSERT INTO  "T2"."HANA_STG1_ORDERS"
("ORIG_ID","ID_REGION","ID_EMPRESA","ID_PRODUCTOS","NO_ORDEN","CLIENTE",
"CATEGORIA","PLAY_ORD","PLAY_CLI","FECHA","MES_1","ANIO_1",
"MIGRACIONES_IZZI_DOWNSALE", "MIGRACIONES_IZZI_INSTALACIONES")
SELECT DISTINCT 
	3 AS ORIG_ID , C.CIUDAD_ID AS ID_REGION, 3 AS ID_EMPRESA, 
	P.ID AS ID_PRODUCTOS, O.NO_ORDEN, C.CLIENTE, P.CATEGORIA, 
	MAP (LENGTH (M.PLAY_IZZI),  1, '1 PLAY',  2, '2 PLAY',  3, '3 PLAY') 
	AS PLAY_ORD, M.PLAY_IZZI, O.FECHA_CREACION AS FECHA, 
	ADD_MONTHS(O.FECHA_CREACION,1) AS MES_1,
	ADD_YEARS(O.FECHA_CREACION,1) AS ANIO_1, 1 AS MIGRACIONES_IZZI_DOWNSALE,
	CASE WHEN FECHA_PROGRAMACION IS NOT NULL AND UPPER(E.ESTATUS) 
		IN ('COMPLETA', 'FINALIZADA', 'ENVIADA') THEN 1 END 
		AS MIGRACIONES_IZZI_INSTALACIONES
FROM 		T1.HANA_STG1_MT_CLIENTES C,
			T1.HANA_STG1_MT_ORDENES O,
			T1.HANA_STG1_CAT_TIPO_ORD T,
			T1.HANA_STG1_MT_ORDENES_ITEM I,
			T1.HANA_STG1_CAT_PRODUCTOS P,
			T1.HANA_STG1_DIM_REGION R,
			T1.HANA_STG1_CAT_ORD_ESTATUS E,
			"#MI_TVI" M		
	WHERE	C.CTA_MIGRADA 	= 	O.CLIENTE_ID 
		AND	O.ORIG_ID 		= 	T.ORIG_ID
		AND	O.TIPO_ORDEN_ID = 	T.ID
		AND O.ORIG_ID		=	I.ORIG_ID
		AND	O.NO_ORDEN		=	I.ORDER_ID
		AND	I.ORIG_ID		=	P.ORIG_ID
		AND	I.PRODUCTO_ID	=	P.ID
		AND C.CIUDAD_ID		=	R.ID
		AND O.ORIG_ID		=	E.ORIG_ID
		AND O.ESTATUS_ORD_ID	=	E.ID
		AND C.CLIENTE 		=	M.CLIENTE
		AND C.CLIENTE IN (
	SELECT CLIENTE 
	FROM "#MI_TVI"
	WHERE TIPO = 'DOWNSALE'
				)
		AND C.ORIG_ID = 3
		AND O.ORIG_ID = 4
		AND	FLG_CTE_MIGRADO = 'Y'
		AND UPPER(E.ESTATUS) != 'CANCELADO'
		AND	O.TIPO_ORDEN_ID = '100' --Orden de Migración Izzi
		AND	UPPER(P.TIPO) IN ('SERVICIO')
		AND	UPPER(P.PRODUCTO) NOT IN ('SERVICIOS ON DEMAND')
		AND CASE WHEN LOCATE(M.PLAY_IZZI, 
		CASE WHEN CATEGORIA = 'VIDEO' THEN 'V' 
		 WHEN CATEGORIA = 'INTERNET' THEN 'I'
		 WHEN CATEGORIA = 'TELEFONIA' THEN 'T'
		END) != '0' THEN 1 END IS NULL
		AND O.FECHA_CREACION BETWEEN ADD_DAYS(:V_IN_DATE,-60) 
								AND :V_IN_DATE
;

--NM
INSERT INTO "T2"."HANA_STG1_ORDERS"
("ORIG_ID","ID_REGION","ID_EMPRESA","ID_PRODUCTOS","NO_ORDEN","CLIENTE",
"CATEGORIA","PLAY_ORD","PLAY_CLI","FECHA","MES_1","ANIO_1",
"MIGRACIONES_IZZI_NM", "MIGRACIONES_IZZI_REALIZADAS_NM")
SELECT DISTINCT 
	3 AS ORIG_ID , C.CIUDAD_ID AS ID_REGION, 3 AS ID_EMPRESA, 
	P.ID_PRODUCTO AS ID_PRODUCTOS, O.NO_ORDEN, C.CLIENTE, P.CATEGORIA, 
	MAP (LENGTH (M.PLAY_IZZI),  1, '1 PLAY',  2, '2 PLAY',  3, '3 PLAY') 
	AS PLAY_ORD, M.PLAY_IZZI, O.FECHA_CREACION AS FECHA, 
	ADD_MONTHS(O.FECHA_CREACION,1) AS MES_1,
	ADD_YEARS(O.FECHA_CREACION,1) AS ANIO_1, 1 AS MIGRACIONES_IZZI_NM,
	CASE WHEN FECHA_PROGRAMACION IS NOT NULL AND UPPER(E.ESTATUS) 
		IN ('COMPLETA', 'FINALIZADA', 'ENVIADA') THEN 1 END 
		AS MIGRACIONES_IZZI_REALIZADAS_NM
FROM 		T1.HANA_STG1_MT_CLIENTES C,
			T1.HANA_STG1_MT_ORDENES O,
			T1.HANA_STG1_CAT_TIPO_ORD T,
			T1.HANA_STG1_MT_ORDENES_ITEM I,
			T1.HANA_STG1_CAT_ITEMS_RGU P,
			T1.HANA_STG1_DIM_REGION R,
			T1.HANA_STG1_CAT_ORD_ESTATUS E,
			"#MI_TVI" M		
	WHERE	C.ORIG_ID		=	O.ORIG_ID
		AND	C.CLIENTE 		= 	O.CLIENTE_ID 
		AND	O.ORIG_ID 		= 	T.ORIG_ID
		AND	O.TIPO_ORDEN_ID = 	T.ID
		AND O.ORIG_ID		=	I.ORIG_ID
		AND	O.NO_ORDEN		=	I.ORDER_ID
		AND	I.ORIG_ID		=	P.ORIG_ID
		AND	I.PRODUCTO_ID	=	P.ID_PRODUCTO
		AND C.CIUDAD_ID		=	R.ID
		AND O.ORIG_ID		=	E.ORIG_ID
		AND O.ESTATUS_ORD_ID	=	E.ID
		AND C.CLIENTE 		=	M.CLIENTE
		AND C.CLIENTE IN (
	SELECT CLIENTE 
	FROM "#MI_TVI"
	WHERE TIPO = 'NM'
				)
		AND C.ORIG_ID = 3
		AND	P.KPI = '1'
		AND UPPER(E.ESTATUS) != 'CANCELADO'
		AND T.TIPO_ORDEN = 'INSTALACION'
		AND O.FECHA_CREACION BETWEEN ADD_DAYS(:V_IN_DATE,-60) 
								AND :V_IN_DATE
;

DROP TABLE "#MI_TVI";

END;
